version: '3.8'

services:
  rabbitmq:
    build:
      context: ./rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  order:
    build:
      context: ./order
    depends_on:
      - rabbitmq
    ports:
      - "3000:3000"

  stock:
    build:
      context: ./stock
    depends_on:
      - rabbitmq
    ports:
      - "3001:3001"

  payment:
    build:
      context: ./payment
    depends_on:
      - rabbitmq
    ports:
      - "3002:3002"

  information:
    build:
      context: ./information
    depends_on:
      - rabbitmq
    ports:
      - "3003:3003"
