apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-deployment
  labels:
    app: stock
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stock
  template:
    metadata:
      labels:
        app: stock
    spec:
      containers:
        - name: stock
          image: juanloaiza007/rabbitmq-transaction-stock:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: stock-service
spec:
  selector:
    app: stock
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
