apiVersion: apps/v1
kind: Deployment
metadata:
  name: information-deployment
  labels:
    app: information
spec:
  replicas: 1
  selector:
    matchLabels:
      app: information
  template:
    metadata:
      labels:
        app: information
    spec:
      containers:
        - name: information
          image: juanloaiza007/rabbitmq-transaction-information:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: information-service
spec:
  selector:
    app: information
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
